/// Delimiter-based streaming parser for Claude output.
///
/// Detects structured blocks in claude -p output:
/// - <<<RESULT_START>>> / <<<RESULT_END>>>
/// - <<<BLOCKING>>> / <<<END_BLOCKING>>>

#[derive(Debug, Clone, PartialEq)]
pub enum ParserState {
    Normal,
    InResult,
    InBlocking,
}

#[derive(Debug, Clone, PartialEq)]
pub enum ParseEvent {
    /// Regular output line
    OutputLine(String),
    /// Result block started
    ResultStart,
    /// Result block ended
    ResultEnd,
    /// Blocking question detected (full question text)
    BlockingDetected(String),
    /// Process ended while still in a block
    MalformedEnd { state: ParserState, partial: String },
}

pub const RESULT_START: &str = "<<<RESULT_START>>>";
pub const RESULT_END: &str = "<<<RESULT_END>>>";
pub const BLOCKING_START: &str = "<<<BLOCKING>>>";
pub const BLOCKING_END: &str = "<<<END_BLOCKING>>>";

pub struct StreamParser {
    state: ParserState,
    buffer: String,
}

impl StreamParser {
    pub fn new() -> Self {
        Self {
            state: ParserState::Normal,
            buffer: String::new(),
        }
    }

    pub fn state(&self) -> &ParserState {
        &self.state
    }

    /// Feed a line of output from claude process.
    /// Returns parse events generated by this line.
    pub fn feed_line(&mut self, line: &str) -> Vec<ParseEvent> {
        let trimmed = line.trim();
        let mut events = Vec::new();

        match &self.state {
            ParserState::Normal => {
                if trimmed == RESULT_START {
                    self.state = ParserState::InResult;
                    events.push(ParseEvent::ResultStart);
                } else if trimmed == BLOCKING_START {
                    self.state = ParserState::InBlocking;
                    self.buffer.clear();
                } else {
                    events.push(ParseEvent::OutputLine(line.to_string()));
                }
            }
            ParserState::InResult => {
                if trimmed == RESULT_END {
                    self.state = ParserState::Normal;
                    events.push(ParseEvent::ResultEnd);
                } else {
                    events.push(ParseEvent::OutputLine(line.to_string()));
                }
            }
            ParserState::InBlocking => {
                if trimmed == BLOCKING_END {
                    let question = self.buffer.trim().to_string();
                    self.buffer.clear();
                    self.state = ParserState::Normal;
                    events.push(ParseEvent::BlockingDetected(question));
                } else {
                    if !self.buffer.is_empty() {
                        self.buffer.push('\n');
                    }
                    self.buffer.push_str(line);
                }
            }
        }

        events
    }

    /// Call when the process exits. Returns any pending malformed state.
    pub fn finalize(&mut self) -> Option<ParseEvent> {
        match &self.state {
            ParserState::Normal => None,
            ParserState::InResult => {
                let partial = self.buffer.clone();
                self.buffer.clear();
                self.state = ParserState::Normal;
                Some(ParseEvent::MalformedEnd {
                    state: ParserState::InResult,
                    partial,
                })
            }
            ParserState::InBlocking => {
                let partial = self.buffer.clone();
                self.buffer.clear();
                self.state = ParserState::Normal;
                Some(ParseEvent::MalformedEnd {
                    state: ParserState::InBlocking,
                    partial,
                })
            }
        }
    }
}

/// Build the prompt preamble that instructs Claude to use delimiters.
pub fn delimiter_preamble() -> String {
    format!(
        r#"IMPORTANT: Structure your response using these exact delimiters:
{RESULT_START}
[your response here]
{RESULT_END}

If you need user input to proceed, output:
{BLOCKING_START}
[your question here]
{BLOCKING_END}
"#
    )
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn normal_output_passthrough() {
        let mut parser = StreamParser::new();
        let events = parser.feed_line("Hello world");
        assert_eq!(events, vec![ParseEvent::OutputLine("Hello world".into())]);
    }

    #[test]
    fn result_block_detection() {
        let mut parser = StreamParser::new();

        let e1 = parser.feed_line(RESULT_START);
        assert_eq!(e1, vec![ParseEvent::ResultStart]);
        assert_eq!(*parser.state(), ParserState::InResult);

        let e2 = parser.feed_line("some content");
        assert_eq!(e2, vec![ParseEvent::OutputLine("some content".into())]);

        let e3 = parser.feed_line(RESULT_END);
        assert_eq!(e3, vec![ParseEvent::ResultEnd]);
        assert_eq!(*parser.state(), ParserState::Normal);
    }

    #[test]
    fn blocking_detection() {
        let mut parser = StreamParser::new();

        let e1 = parser.feed_line(BLOCKING_START);
        assert!(e1.is_empty()); // No event yet, buffering
        assert_eq!(*parser.state(), ParserState::InBlocking);

        let _ = parser.feed_line("Which file should I modify?");
        let _ = parser.feed_line("I see src/main.rs and src/lib.rs");

        let e2 = parser.feed_line(BLOCKING_END);
        assert_eq!(
            e2,
            vec![ParseEvent::BlockingDetected(
                "Which file should I modify?\nI see src/main.rs and src/lib.rs".into()
            )]
        );
        assert_eq!(*parser.state(), ParserState::Normal);
    }

    #[test]
    fn malformed_end_in_result() {
        let mut parser = StreamParser::new();
        let _ = parser.feed_line(RESULT_START);
        let _ = parser.feed_line("partial content");

        let event = parser.finalize();
        assert!(matches!(
            event,
            Some(ParseEvent::MalformedEnd {
                state: ParserState::InResult,
                ..
            })
        ));
    }

    #[test]
    fn malformed_end_in_blocking() {
        let mut parser = StreamParser::new();
        let _ = parser.feed_line(BLOCKING_START);
        let _ = parser.feed_line("incomplete question");

        let event = parser.finalize();
        assert!(matches!(
            event,
            Some(ParseEvent::MalformedEnd {
                state: ParserState::InBlocking,
                ..
            })
        ));
    }

    #[test]
    fn finalize_normal_returns_none() {
        let mut parser = StreamParser::new();
        let _ = parser.feed_line("just text");
        assert!(parser.finalize().is_none());
    }

    #[test]
    fn no_delimiters_fallback() {
        let mut parser = StreamParser::new();
        let e1 = parser.feed_line("line 1");
        let e2 = parser.feed_line("line 2");
        let e3 = parser.feed_line("line 3");

        assert_eq!(e1, vec![ParseEvent::OutputLine("line 1".into())]);
        assert_eq!(e2, vec![ParseEvent::OutputLine("line 2".into())]);
        assert_eq!(e3, vec![ParseEvent::OutputLine("line 3".into())]);
        assert!(parser.finalize().is_none());
    }

    #[test]
    fn delimiter_preamble_contains_markers() {
        let preamble = delimiter_preamble();
        assert!(preamble.contains(RESULT_START));
        assert!(preamble.contains(RESULT_END));
        assert!(preamble.contains(BLOCKING_START));
        assert!(preamble.contains(BLOCKING_END));
    }
}
